---
stages:
  - test

test run_command script:
  stage: test
  tags:
    - k8s-unpriv
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
#   - pip install -r requirements.txt
    - pip install --upgrade pip
    - pip install six posttroll pyinotify prometheus_client trollsift
    - python bin/pytroll-run-command.py test
