---
stages:
  - test

test run_command script:
  stage: test
  tags:
    - k8s-unpriv
  script:
    - which python
    - which python3
    - /usr/bin/python test run_command.py
    - /usr/bin/python3 test run_command.py